In [1]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1, arr2))
print(arr)


[1 2 3 4 5 6]


In [3]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [27]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.split(arr,6)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [35]:
import numpy as np
arr=np.array([1,2,5,6])
newarr=np.hsplit(arr,2)
print(newarr)

[array([1, 2]), array([5, 6])]


In [44]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=np.where(arr==4)
print(x)


(array([3], dtype=int64),)


In [65]:
A=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(np.linalg.matrix_rank(A))

2


In [2]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1, arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [4]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]
