In [23]:
import numpy as np
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr1)
print(arr1[0:3,0:2])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [ ]:
import numpy as np
org_array = np.array(